### ISSUE TITLE
jslint version question

### ISSUE THREAD

**Issue by pantocrator27** [karimsa/gulp-jslint#27]
Hello.  It has just come to my attention that when the node-jslint uses an old version of jslint from Aug 2013 unless the edition information is specifying as being the latest.  That being said, I was curious about two things.  1) What version of jslint does gulp-jslint default to? 2) Is there a way to configure gulp-jslint to control which version of jslint node-jslint is using?

Thanks in advance!

**Comment by karimsa** [comment]
Hi, there.

Currently, gulp-jslint uses the latest available version of jslint to lint the code. Personally, I feel this is the best way to do things since this would only be an issue if projects updated their gulp-jslint dependency version and didn't test to see if the new jslint passes their code. However, this issue still raises a valid point, and since I do not want to be opinionated, I will add an option for specifying the jslint version number.

**Comment by pantocrator27** [comment]
I was just curious since node - jslint is not setup to use the latest
version by default.  I look (very briefly) and could not find a reference
to using the option to use the latest.  I am not opposed to always using
the latest version.

**Comment by karimsa** [comment]
I still think this deserves an option for any packages that wish to use a frozen version of jslint.
